import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Sidebar
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

// Header
import AppHeader from "@/components/app-header";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased dark text-[14px]`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full p-4 sm:p-6 overflow-x-clip">
            <AppHeader />
            <div className="max-w-[1320px] mx-auto">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
