import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Sidebar
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

// Header
import AppHeader from "@/components/app-header";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased dark`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full p-6">
            <AppHeader />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
