import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Sidebar
import { AppSidebar } from "@/src/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/src/components/ui/sidebar";

// Header
import AppHeader from "@/src/components/app-header";

import "./globals.css";
import { AuthProvider } from "@/src/contexts/AuthContext";
import { Toaster } from "@/src/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased dark text-[14px]`}>
        <AuthProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <main className="w-full min-h-[100vh] flex-1 rounded-lg bg-muted md:min-h-min px-4 py-2 md:px-11">
                <AppHeader />
                <div className="max-w-[1320px] mx-auto px-2 sm:px-4">
                  {children}
                </div>
                <footer className="h-[20px] mb-2 mt-10 sm:mt-14" />
              </main>
              <Toaster />
            </SidebarInset>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
